name: CI

on:
  push:
    branches:
      - '**'
  release:
    types: [published]

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Tests
        run: go test -v ./...
